### ISSUE TITLE
Permitir que US informe quantas vagas foram efetivamente utilizadas

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/RPES#118]
# Objetivo

**Eu como** pessoa usuária do sistema RPES
**Quero** visualizar o número de vagas que foram utilizadas ou não, sendo as mesmas informadas pelo Local de Práticas
**Para que** não haja comprometimento de vaga de forma desnecessária.

# Contexto
## O que originou
- Atualmente não há discriminação do número de vagas que realmente foram utilizadas após solicitação, deixando em aberto esse feedback. Desta forma, as vagas continuam comprometidas, não permitindo verdadeira noção do seu aproveitamento.

## Qual solução proposta
-[] Criação de um campo dentro da solicitação que permita a discriminação das vagas realmente utilizadas após deferimento.

# Critérios de aceitação

Deve haver um campo dentro da solicitação onde a US possa informar o quantitativo de vagas efetivamente utilizadas.

**Comment by drmarcos** [comment]
Essa permissão é feita onde? Pode descreve-la?

**Comment by drmarcos** [comment]
Essa permissão é feita onde? Pode descreve-la?
