### ISSUE TITLE
Exibir o campo "Semestre da disciplina" na visualização da solicitação de estágio supervisionado

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/RPES#182]
O valor do campo "semestre" da view vwsolicitacoes deve ser mostrado ao usuário admin na tela de visualização do conteúdo da solicitação de estágio supervisionado.

**Comment by drmarcos** [comment]
Modificação realizada em 21/07/2021
\admin\consultas\solicitacao.php
\lib\admin\consultas\solicitacao.php
$_SESSION["filtros"] precisa rever? Existem datas fixas no arquivo!
