### ISSUE TITLE
Criar funcionalidade para desativar Instituição.

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/RPES#183]
Na tabela "Instituições" existe um campo "situacao". True=ativo / Falso=inativo. Na tela de Consultas --> Instituições, quando o usuário ADMIN clicar no ícone do lixo, esta funcionalidade deve setar o campo para false. (Algo semelhante já está implementado em Consultas --> Usuários). Lembrar de implementar o botão para desfazer a ação (seta circular).

Desdobramentos:

- [x] Impedir que o usuário de uma instituiçao inativa faça login.
- [x] Se a instituição desativada for US, ela não deve aparecer na listagem de US disponíveis para solicitação de vagas (perfil painel, formulários de solicitação de estágio graduação, estágio pós, internato, prática assistida e visita técnica).
- [x] A instituição não deve aparecer na listagem para cadastramento de novos usuários.
- [x] A instituição não deve aparecer na listagem para cadastramento de novos serviços.

Arquivos alterados

- [x] LIB/login.php

- [x] ADMIN/CONSULTAS/instituicao.php

- [x] LIB/ADMIN/CONSULTAS/instituicao.php

- [x]  LIB/PAINEL/CADASTROS/editar_solicitacao_internato.php

- [x]  LIB/PAINEL/CADASTROS/editar_solicitacao_estagio_grad.php

- [x]  LIB/PAINEL/CADASTROS/editar_solicitacao_estagio_pos.php

- [x]  LIB/PAINEL/CADASTROS/editar_solicitacao_visita.php

- [x]  LIB/PAINEL/CADASTROS/editar_solicitacao_pa.php

- [x] ADMIN/CADASTROS/editar_usuario.php

- [x] LIB/ADMIN/CADASTROS/editar_usuario.php

- [x] ADMIN/CADASTROS/editar_servico.php

- [x] LIB/ADMIN/CADASTROS/editar_servico.php

**Comment by drmarcos** [comment]
* Impedir que o usuário de uma instituição inativa faça login.
LIB/login.php
* Recurso para ativar e desativar uma instituição 
ADMIN/CONSULTAS/instituicao.php
LIB/ADMIN/CONSULTAS/instituicao.php

**Comment by drmarcos** [comment]
A instituição não deve aparecer na listagem para cadastramento de novos usuários.
arquivo modificado:: ADMIN/CADASTROS/editar_usuario.php

**Comment by drmarcos** [comment]
* A instituição não deve aparecer na listagem para cadastramento de novos serviços.
ADMIN/CADASTROS/editar_servico.php

**Comment by drmarcos** [comment]
* Precisamos conversar sobre:
 Se a instituição desativada for US, ela não deve aparecer na listagem de US disponíveis para solicitação de vagas 
 (perfil painel, formulários de solicitação de estágio graduação, estágio pós, internato, prática assistida e visita técnica).

**Comment by camilaccolares** [comment]
Após testes, foram identificados os seguintes problemas:

- Usuário pertencente a instituição inativa está conseguindo fazer login normalmente (testado US e IES)
- No perfil IES, no formulário de solicitação de internato, não aparecem na listagem de US as instituições provenientes do convênio com ISGH
- No perfil IES, corrigir nome das US nos menus dropdown de todos os 5 formulários de solicitações

**Comment by drmarcos** [comment]
Resolvido
* Modificado também o arquivo lib/consultas/instituicoes.php (criação de ancora para mudança de status)
