### ISSUE TITLE
Criar formulário para solicitação de Internato de Enfermagem.

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/RPES#188]
- [x] Criar um novo tipo de prática chamada Internato Enfermagem
- [x] Renomear o internato existente para Internato Medicina
- [x] Alterar o código das práticas de internato do curso de enfermagem para o novo código

- [x] No formulário de Internato Medicina, travar o curso_id para medicina. Retirar os campos para preenchimento do tipo de curso e curso. Definir esses valores no back de forma estática.

- [x] Criar um novo formulário para Internato Enfermagem, travando também o curso_id e o tipo de solicitação.

- [x] Alterar nome do link de Internato Medicina

- [x] Criar link para Internato Enfermagem

**Comment by drmarcos** [comment]
É interessante deixar claro onde isso é feito.
Será um subitem de cadastros? Acredito que sim!
"Criar uma nova modalidade chamada Internato Enfermagem" é esse subitem?
Esse é uma atividade para gerentes também?
Acredito que não, pois o menu para gerentes /cadastros não possui o subitem "internato"

**Comment by marameida** [comment]
Reforçado em reunião com HGF (25/10/2021) a necessidade de formulário separado, incluindo locais especificados para o curso. @drmarcos e @camilaccolares
