### ISSUE TITLE
Relatórios 2021.1 e 2021.2

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/RPES#196]
- [x] Admin
- [x] IES
- [x] US
- [x] Gerente

**Comment by drmarcos** [comment]
_Demanda realizado hoje (26/07/2021)_
**Arquivos alterados**
Com base nas informações obtidas com José Luis os seguintes arquivos foram modificados:
\admin\relatorios\relatorios.php
\lib\admin\relatorios\relatorios.php
\admin\relatorios\detalhadoies.php
\admin\relatorios\detalhadous.php
\admin\relatorios\geralies.php
\admin\relatorios\geralus.php
\admin\relatorios\graduacaous.php
\admin\relatorios\internatodeferidasIES.php
\admin\relatorios\internatodeferidasUS.php
\backup_bd\estagios\admin\relatorios\detalhadoies.php
\backup_bd\estagios\admin\relatorios\detalhadous.php
\backup_bd\estagios\admin\relatorios\geralies.php
\backup_bd\estagios\admin\relatorios\geralus.php
\backup_bd\estagios\admin\relatorios\graduacaous.php
\backup_bd\estagios\admin\relatorios\internatodeferidasIES.php
\backup_bd\estagios\admin\relatorios\internatodeferidasUS.php
