### ISSUE TITLE
Novo relatório detalhado de internos deferidos

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/RPES#198]
Deve ser criado um relatório usando o resultado da seguinte consulta:

select codigo, nomeinstituicao_destino as unidade, data_inicio, data_fim, servicosolicitado, aluno  from vwsolicitacoes
where (situacao = 2 or situacao = 4) -- deferida ou parcialmente deferida
and fktiposolicitacao = 2 -- internato
and fkcodcurso = 7 -- medicina
and fkcodinstituicao_origem = <<cod da ies>> -- codigo da instituicao de ensino
and (
	(data_inicio >= '2021-07-01' and data_inicio <= '2021-07-31' and data_fim >= '2021-07-01' and data_fim <= '2021-07-31') -- inicia e finaliza dentro do mes
	or (data_inicio >= '2021-07-01' and data_inicio <= '2021-07-31' and data_fim > '2021-07-31') -- inicia no mes e finaliza em outro
	or (data_inicio < '2021-07-01' and data_fim >= '2021-07-01' and data_fim <= '2021-07-31') -- inicia antes do mes e termina no mes
	or (data_inicio < '2021-07-01' and data_fim > '2021-07-31') -- inicia antes do mes e termina apos o mes
)
order by unidade asc, aluno asc

Para o perfil admin deve haver uma caixa de seleção onde o usuário seleciona a IES. 

Para o perfil da IES, o codigo da IES deve ser o código da instituicao do usuário logado.

**Comment by drmarcos** [comment]
/* --------------------------------------------------------------------------- */
// RELATORIO Relatório Internato Deferidos IES entrega (13/08/2021)
/* --------------------------------------------------------------------------- */
config.inc.owp.php
\lib\params.inc.owp.php
\lib\params.relatorios.inc.owp.php
\ADMIN/RELATORIOS\imprime.rel.internato.deferido.inc.php
\LIB\ADMIN\RELATORIOS\relatorios_internos_deferidos.php
\LIB\ADMIN\LIB\RELATORIOS\relatorios_internos_deferidos.php

Lembrando que é preciso mudar os dados no arquivo config para conexão com o banco de dados e a localização de arquivos para a variável $INCLUDE (caminho físico);

**Comment by drmarcos** [comment]
/* --------------------------------------------------------------------------- */
// RELATORIO Relatório Internato Deferidos IES entrega (16/08/2021) IES
/* --------------------------------------------------------------------------- */
painel\menu.php
\PAINEL/RELATORIOS\imprime.rel.internato.deferido.inc.php
\LIB\PAINEL\RELATORIOS\relatorios_internos_deferidos.php
\LIB\PAINEL\LIB\RELATORIOS\relatorios_internos_deferidos.php
