### ISSUE TITLE
Desbobramentos issue #96

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/RPES#210]
Com a criação de um novo status de solicitação, é necessário realizar ajustes nos perfis.

IES 
- [x] Exibir corretamente a situação no grid de consulta de solicitações
- [x] Exibir corretamente a situação na visualização da solicitação
- [x] Incluir situação no menu dropdown de filtro na tela de consulta de solicitações

US
- [x] Exibir corretamente a situação no grid de consulta de solicitações
- [x] Exibir corretamente a situação na visualização da solicitação (imprimir)
- [x] Exibir corretamente a situação na tela de resposta da solicitação 
- [x] Incluir situação no menu dropdown de filtro na tela de consulta de solicitações

ADMIN
- [x] Exibir corretamente a situação no grid de consulta de solicitações
- [x] Exibir corretamente a situação na visualização da solicitação
- [x] Incluir situação no menu dropdown de filtro na tela de consulta de solicitações

GERENTE
- [x] Exibir corretamente a situação no grid de consulta de solicitações
- [x] Exibir corretamente a situação na visualização da solicitação (imprimir)
- [x] Exibir corretamente a situação na tela de resposta da solicitação 
- [x] Incluir situação no menu dropdown de filtro na tela de consulta de solicitações

**Comment by drmarcos** [comment]
Finalizando as modificações nos 24 arquivos

LIB/us/consultas/solicitacao.php
LIB/us/consultas/exibir_solicitacao_estagio_visita.php
LIB/us/consultas/exibir_solicitacao_estagio_pa.php
LIB/us/consultas/exibir_solicitacao_estagio_pos.php
LIB/us/consultas/exibir_solicitacao_estagio.php
LIB/us/consultas/exibir_solicitacao_internato.php
LIB/IES/consultas/solicitacao.php
LIB/IES/consultas/exibir_solicitacao_internato.php
LIB/IES/consultas/exibir_solicitacao_estagio.php
LIB/IES/consultas/exibir_solicitacao_estagio_visita.php
LIB/IES/consultas/exibir_solicitacao_estagio_pa.php
LIB/IES/consultas/exibir_solicitacao_estagio_pos.php
LIB/GERENTE/consultas/solicitacao.php
LIB/GERENTE/consultas/exibir_solicitacao_estagio.php
LIB/GERENTE/consultas/exibir_solicitacao_internato.php
LIB/GERENTE/consultas/exibir_solicitacao_pos.php
LIB/GERENTE/consultas/exibir_solicitacao_pa.php
LIB/GERENTE/consultas/exibir_solicitacao_estagio_visita.php
LIB/ADMIN/consultas/solicitacao.php
LIB/ADMIN/consultas/imprimir_solicitacao_estagio.php
LIB/ADMIN/consultas/imprimir_solicitacao_internato.php
LIB/ADMIN/consultas/imprimir_solicitacao_pos.php
LIB/ADMIN/consultas/imprimir_solicitacao_pa.php
LIB/ADMIN/consultas/imprimir_solicitacao_estagio_visita.php

Ao final dos testes enviarei os arquivos

**Comment by drmarcos** [comment]
Arquivos transferidos para VM e testados
Arquivos compactados e enviados
