### ISSUE TITLE
Incluir nos relatórios a logo da Escola de Saúde Pública

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/RPES#236]
# Objetivo

**Eu como** pessoa usuária do RPES
**Quero** incluir nos relatórios a logo da Escola de Saúde Pública
**Para que** os documentos sejam melhor identificados quanto ao seu vínculo com a Instituição.

# Contexto
## O que originou
_ Atualmente os relatórios não apresentam a logo da ESP. A identificação se faz importante pois reforça nos documentos a existência de um vínculo institucional firmado.

## Qual solução proposta
- [x] Ajustar arquivo atual, incluindo nova logo

# Critérios de aceitação

- [x] **Dado que** após atualização de relatórios
**Quando** o usuário acessar os arquivos
**Então**poderá visualizar a logo da SESA e da ESP

# Observações

_

**Comment by camilaccolares** [comment]
Realizado nos perfis:

- [x] Admin
- [x] Gerente
- [x] IES
- [x] US
