### ISSUE TITLE
Realizar solicitação para prática assistida aos sábados

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/RPES#272]
# Objetivo

**Eu como**  pessoa usuária do RPES
**Quero** incluir o "sábado" como data possível de prática assistida
**Para que** as solicitações neste dia sejam possíveis

# Contexto
## O que originou
- Atualmente o sistema não permite solicitação para o "sábado"

## Qual solução proposta
- Incluir o "sábado " como período viável às solicitações de prática assistida

# Critérios de aceitação

- [ ] **Dado que** ao incluir o sábado no sistema
**Quando** realizada solicitação de prática
**Então** será possível também neste dia.

**Comment by camilaccolares** [comment]
Esta foi uma demanda pontual do HGCC e não será incluída como regra de negócio no sistema. Caso necessário, os dias da solicitação serão alterados diretamente no banco de dados.
