### ISSUE TITLE
Iniciar implementação de modificações no "dashboard" 

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/RPES#275]
# Objetivo

**Eu como** pessoa usuária do RPES 
**Quero** implementar modificações no "dashboard"
**Para que** seja possível detalhamento e avaliação de novos indicadores.

# Contexto
## O que originou

- O Dashboard atual do RPES discrimina gráficos de indicadores quanto às solicitações e vagas. São especificados dados de: Solicitações por Ano; Solicitações por Situação; Solicitações por Unidade de Saúde; Solicitações por Instituição de Ensino Superior; Solicitações por curso; Vagas deferidas por Unidade de Saúde; Vagas deferidas por IES; Vagas deferidas por Curso.

## Qual solução proposta
Sugestões para posterior refinamento:

- [x] Incluir percentuais no indicador "solicitações por situação" (modificar gráfico para formato de pizza);
- [x] Levantamento do tempo médio entre realização da solicitação e resposta por US;
- [x] Ranking das IEs em relação à quantidade de cancelamentos;
- [x] Proporção de Indeferidos para o perfil IEs;
- [x] Proporção de indeferidos para o perfil US;
- [x] Inclusão de Gráficos discriminando solicitações e vagas por "tipo de prática";
- [ ] Inclusão de descrição de cursos nas US  com maior prevalência nas vagas deferidas;
- [x] Organizar percentuais dos gráficos por ordem crescente;
- [ ] Organizar dados especificando os períodos;
- [ ] Atualizar status de solicitações no gráfico "solicitações por situação";
- [ ] Discriminar os motivos principais para respostas de vagas "indeferidas"  e "parcialmente deferidas";
- [ ] Dados disponíveis por usuário (incluir filtros ou adequar para cada acesso específico - iniciar com perfil GERENTE) (Refinar);
- [ ] Incluir regiões e municípios (ainda não implantado no sistema);

# Critérios de aceitação

- [ ] **Dado que** após refinamento das demandas
**Quando** cada atividade estiver sendo trabalhada de forma independente
**Então** será possível fechamento deste card.

**Comment by marameida** [comment]
@aislansf registrado aqui mais algumas sugestões de tratamento para os indicadores.

**Comment by marameida** [comment]
Demandas refinadas. Serão divididas em dois blocos:
- Atividades possíveis (VERSÃO 1);
- Atividades pendentes por necessitar de equipe de desenvolvimento (VERSÃO 2);

**Comment by aislansf** [comment]
Dashboard do RPES
https://metabase.dev.org.br/dashboard/298-rpes

**Comment by aislansf** [comment]
2º tarefa.
É importante analisar os casos que apresentam dados "vázios", podendo ser representados por um valor.

**Comment by aislansf** [comment]
@marameida acho interessante colocarmos às últimas atividades não realizadas em um outro card, até pq temos a dependência de time de desenvolvimento para dar continuidade. O que você acha ?

**Comment by aislansf** [comment]
Dashboard atualizada do RPES
https://metabase.esp.ce.gov.br/public/dashboard/f70e2d8d-0355-481c-a3aa-a78980ebd9b7
