### ISSUE TITLE
Automatizar abertura do RPES para que possa ser gerenciável pelo perfil ADM

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/RPES#294]
# Objetivo

**Eu como** pessoa usuária do sistema RPES
**Quero** automatizar abertura do RPES
**Para que** o perfil ADM possa gerenciar o sistema de forma mais independente.

# Contexto
## O que originou
- Hoje o sistema é aberto e fechado diretamente via código pela @camilaccolares, sendo as datas repassadas e acordadas entre educação permanente, instituições de ensino e unidades de saúde. 

## Qual solução proposta
- Automatizar a abertura do sistema, disponibilizando para o usuário ADM uma funcionalidade onde ele pode informar as datas de abertura e fechamento de cada tipo de prática no sistema

**Comment by camilaccolares** [comment]
- [x] Criar tela para controle de datas de abertura e de datas de semestre para cada tipo de pratica
- [x] Ajustar menu do perfil IES para exibir as opções de solicitações conforme as datas de abertura

Ajustar formulários de solicitações para impedir que sejam inseridas solicitações para práticas que ocorrerão fora do período do semestre
- [x] Estágio supervisionado técnico/graduação
- [x] Estágio supervisionado pós-graduação
- [x] Internato Medicina
- [x] Internato Enfermagem
- [x] Prática assistida
- [x] Visita técnica
