### ISSUE TITLE
Restringir as opções de respostas de solicitações para usuários US

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/RPES#305]
# Objetivo
Na tela de resposta de solicitações, restringir as opções de respostas para somente:
- Deferida aguardando documentação
- Parcialmente Deferida aguardando documentação
- Indeferida

# Contexto
Atualmente, na tela de resposta de solicitações são exibidos todos os possíveis status de uma solicitação. Entretanto, alguns desses status não podem ser atribuídos diretamente pelo usuário US, o que pode causar confusão no momento da resposta. Assim, propõe-se limitar as opções que podem ser escolhidas pelo usuário, evitando que eles escolham alguma opção inválida.

## Qual solução proposta
Criar um campo com radio buttons exibindo somente as opções que podem de fato ser escolhidas pelo usuário US. Atualmente são elas:
- Deferida aguardando documentação
- Parcialmente Deferida aguardando documentação
- Indeferida

## Critérios de aceitação
As seguintes páginas devem estar ajustadas ao novo layout:

- [x] Tela de resposta de Estágio Supervisionado técnico/graduação
- [x] Tela de resposta de Estágio Supervisionado pós-graduação
- [x] Tela de resposta de Internato
- [x] Tela de resposta de Prática Assistida
- [x] Tela de resposta de Visita Técnica
- [x] Inserir asterisco de obrigatoriedade no campo Situação
- [x] Corrigir texto de obrigatoriedade no campo Justificativa

**Comment by marameida** [comment]
Atividade finalizada. @camilaccolares
