### ISSUE TITLE
Atualizações DASHBOARD (Fase 1):

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/RPES#315]
# Objetivo

**Eu como** pessoa usuária do RPES 
**Quero** implementar modificações no "dashboard"
**Para que** seja possível detalhamento e avaliação de novos indicadores.

# Contexto
## O que originou

- O Dashboard atual do RPES discrimina gráficos de indicadores quanto às solicitações e vagas. São especificados dados de: Solicitações por Ano; Solicitações por Situação; Solicitações por Unidade de Saúde; Solicitações por Instituição de Ensino Superior; Solicitações por curso; Vagas deferidas por Unidade de Saúde; Vagas deferidas por IES; Vagas deferidas por Curso.

## Qual solução proposta
Sugestões para posterior refinamento:

- [x] Incluir percentuais no indicador "solicitações por situação" (modificar gráfico para formato de pizza);
- [x] Levantamento do tempo médio entre realização da solicitação e resposta por US;
- [x] Ranking das IEs em relação à quantidade de cancelamentos;
- [x] Proporção de Indeferidos para o perfil IEs;
- [x] Proporção de indeferidos para o perfil US;
- [x] Inclusão de Gráficos discriminando solicitações e vagas por "tipo de prática";
- [x] Inclusão de descrição de cursos nas US  com maior prevalência nas vagas deferidas;
- [x] Organizar percentuais dos gráficos por ordem crescente;
- [x] Organizar dados especificando os períodos;

# Critérios de aceitação

- [x] **Dado que** após atividades concluídas  
**Quando** usuário ADM acessar o sistema
**Então** contará com novas melhorias.

**Comment by marameida** [comment]
@aislansf seguimos por aqui. Fechei o card anterior.

**Comment by aislansf** [comment]
Segue link da dashboard
https://metabase.esp.ce.gov.br/public/dashboard/f70e2d8d-0355-481c-a3aa-a78980ebd9b7

**Comment by marameida** [comment]
Atividades finalizadas. No aguardo pela formação da equipe de desenvolvimento para darmos seguimento às demais modificações.
