### ISSUE TITLE
<IEs fez solicitação de "estágio supervisionado" com o sistema fechado para solicitação dessa prática > ...

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/RPES#321]
## **Descrição**
IEs fez solicitação de "estágio supervisionado" com o sistema fechado para solicitação dessa prática.
Solicitação nº 43920
Instituição: Centro Universitário INTA
Serviços: Divisão de Biologia Médica
Curso: Graduação em Medicina Veterinária
Disciplina: Estágio Supervisionado Obrigatório

## **Observações**
Verificar se a pessoa usuária não fez a solicitação usando o formulário da pós-graduação

**Comment by camilaccolares** [comment]
Solicitação de estágio supervisionado de graduação realizada no formulário correto (nome análogo). Verificar se a solicitação foi inserida pelo Tiago.

**Comment by marameida** [comment]
Solicitação foi feita pela própria Instituição. Vamos verificar segurança no fluxo de pedidos dependendo do tipo de solicitação.

**Comment by camilaccolares** [comment]
Foi possível para a IES realizar a solicitação devido a uma vulnerabilidade do sistema. Sugere-se criação de um novo card para solucionar esta vulnerabilidade.

**Comment by marameida** [comment]
Ciente. Registrado #326.
