### ISSUE TITLE
<O perfil ADM não está conseguindo abrir as solicitações de "internato de enfermagem"> ...

### ISSUE THREAD

**Issue by marameida** [EscolaDeSaudePublica/RPES#323]
## **Descrição**
O usuário do perfil ADM não está conseguindo abrir as solicitações de "internato de enfermagem"

## **Observações**
Verificar se a dificuldade se apresenta também para os outros tipos de práticas.

**Comment by camilaccolares** [comment]
Problema corrigido no arquivo de controle da página de consulta de solicitações. Os demais perfis foram verificados e nenhum apresentou o mesmo problema.
