### ISSUE TITLE
Acrescentar status "Em atendimento" para que solicitações que já foram visualizadas não possam ser alteradas

### ISSUE THREAD

**Issue by camilaccolares** [EscolaDeSaudePublica/RPES#96]
Atualmente, as situações das solicitações podem ser as seguintes:
0 - Aguardando atendimento
1- Cancelada 
2- Deferida 
3- Indeferida 
4- Parcialmente deferida

É necessário definir um novo tipo de situação denominada "Em atendimento" (5). A solicitação deverá assumir esta situação sempre que estiver com status 0 (aguardando atendimento) e a US entrar na tela para respondê-la. No perfil IES, quando a solicitação estiver em uma situação diferente de 0  (aguardando atendimento) , os dados da solicitação não podem ser alterados.

**Comment by drmarcos** [comment]
Arquivos alterados:
* LIB/us/consultas/solicitacao.php
* LIB/us/consultas/exibir_solicitacao_estagio_visita.php
* LIB/us/consultas/exibir_solicitacao_estagio_pa.php
* LIB/us/consultas/exibir_solicitacao_estagio_pos.php
* LIB/us/consultas/exibir_solicitacao_estagio.php
* LIB/us/consultas/exibir_solicitacao_internato.php
e enviados!
